### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dankerri**
Add description of vibrate props to README, and point out the npm packeage isn't the latest version.

### CODE REVIEW

**Comment by moaazsidat** [comment]
@dankerri wouldn't it be better to update the module to account for the updated package?

**Comment by dankerri** [comment]
Could I ask when do you plan to update the package? Maybe we should keep this until you finish it.

**Comment by moaazsidat** [comment]
I'm currently only contributing essential fixes to this repo, and won't be able to take on implementing the additional scope in the short term. Will accept PRs updating the package.

**Comment by moaazsidat** [comment]
Closing this due to lack of activity, please reopen if still relevant

**Pull request closed without merging**
