### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by jchaves07**
I propose README change, because in the new project to test this awesome package, I get the error when I run the app with the package, I get the error: 

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :react-native-camera.
     Required by:
         project :app
      > Cannot choose between the following variants of project :react-native-camera:
          - generalDebugRuntimeElements
          - mlkitDebugRuntimeElements
```
and I found the solution with this solution: https://github.com/react-native-community/react-native-camera/issues/2276#issuecomment-498022704

### CODE REVIEW

**Comment by jchaves07** [comment]
I propose README change, because in the new project to test this awesome package, I get the error when I run the app with the package, I get the error:

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :react-native-camera.
     Required by:
         project :app
      > Cannot choose between the following variants of project :react-native-camera:
          - generalDebugRuntimeElements
          - mlkitDebugRuntimeElements
and I found the solution with this solution: react-native-community/react-native-camera#2276 (comment)

**Comment by hhwsgit** [comment]
I have the same problem. Have you solved it?

**Comment by bbeckkk** [comment]
https://react-native-community.github.io/react-native-camera/docs/installation

Insert the following lines in android/app/build.gradle:

```
android {
  ...
  defaultConfig {
    ...
    missingDimensionStrategy 'react-native-camera', 'general' // <--- insert this line
  }
}
```

**Comment by renatobenks** [comment]
I'll be merging this one because there's no other workaround to resolve this build setting for gradle builds as it's related to react-native-camera and not directly to this. Thank you for this contributing @jchaves07

**Pull request merged**
