### PR TITLE
Document Android  Support

### PR DESCRIPTION
**Pull request by alexbowers**

### CODE REVIEW

**Comment by alexbowers** [comment]
It seems to work perfectly fine. Here is my file:

```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  Linking
} from 'react-native';

import QRCodeScanner from 'react-native-qrcode-scanner';

export default class qrscanner extends Component {
  onRead(e) {
    Linking.openURL(e.data).catch(err => console.error('An error occurred', err))
  }

  render() {
    return (
      <View style={styles.container}>
        <QRCodeScanner onRead={this.onRead.bind(this)}/>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5FCFF',
  },
});

AppRegistry.registerComponent('qrscanner', () => qrscanner);
```

**Comment by alexbowers** [comment]
Tested on a real Nexus 5.

**Comment by moaazsidat** [comment]
Thanks so much for testing @alexbowers! 🙌

**Comment by alexbowers** [comment]
No problem. All i tested was it recognising a qr code, is there anything else that needs testing?

**Pull request merged**
