### PR TITLE
Upgrade react-native-permissions to v2.0.0

### PR DESCRIPTION
**Pull request by aimawari**

### CODE REVIEW

**Comment by wilifabrizio** [comment]
merge please!!!

**Comment by f0ntana** [comment]
Can merging?

**Comment by kwokhou** [comment]
Tested this on my RN 60 project, works as expected. hope this get merge soon.

**Comment by YisusMB** [comment]
@moaazsidat please merge this :( this fix perfectly the issue w/ react native permissions for ios <3

**Comment by TeruyaHaroldo** [comment]
@moaazsidat I tested and works. Please merge

**Comment by JackyChar** [comment]
Please merge. thanks !

**Comment by ferdiamg** [comment]
Lets get this merged please!

**Comment by manikandasankar** [comment]
Please merge.

Thanks.

**Comment by TeruyaHaroldo** [comment]
Merge please

**Comment by arjun-livquik** [comment]
Guys when will this be merged? If it's taking time looks like better to fork and do the changes and use the fork until this is merged.

**Comment by wellmmer** [comment]
Please merge this one!!!!

**Comment by wilifabrizio** [comment]
@moaazsidat please merge, works correctly

**Comment by olethanh** [comment]
Confirm this work, but I also had to 
1. `yarn add react-native-permissions`  to have the dependencie directly in package .lock
2. Add to my podfile (see react-native-permissions doc https://github.com/react-native-community/react-native-permissions#ios )
```
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
```
3. `cd ios; pod install`
4. `rm -r ios build` (without this the change where not taken into account and the app still crashed with the error "Invalid RNPermission X. Should be one of: ()"
5. If not done before don't forget to mention the permission in your info.plist file
6. re run `react-native run-ios`

**Comment by pemba007** [comment]
**I happen to face this error. Any solution?**

Invalid ios permission "camera". Must be one of:

• ios.permission.BLUETOOTH_PERIPHERAL
• ios.permission.CALENDARS
• ios.permission.CAMERA
• ios.permission.CONTACTS
• ios.permission.FACE_ID
• ios.permission.LOCATION_ALWAYS
• ios.permission.LOCATION_WHEN_IN_USE
• ios.permission.MEDIA_LIBRARY
• ios.permission.MICROPHONE
• ios.permission.MOTION
• ios.permission.PHOTO_LIBRARY
• ios.permission.REMINDERS
• ios.permission.SIRI
• ios.permission.SPEECH_RECOGNITION
• ios.permission.STOREKIT

**Comment by radetsky** [comment]
Would you like to merge it, please?

**Comment by moaazsidat** [comment]
@olethanh since `react-native-permissions` is a dependency of this project already, is there still a need to install it separately?

**Comment by olethanh** [comment]
I had build dependencies problem without it. (Headers not found iirc)

**Comment by moaazsidat** [comment]
@olethanh gotcha, do you think that's something we can add in the readme?

**Comment by olethanh** [comment]
sure

**Pull request merged**
